# Generated by Django 4.2 on 2022-01-01 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.TimeField(default=django.utils.timezone.now)),
                ("stop_time", models.TimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(auto_now=True)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profile", models.ImageField(upload_to="uploads/profile")),
                ("description", models.TextField(default="No description available")),
                ("group_chat", models.BooleanField(default=True)),
                ("is_private", models.BooleanField(default=False)),
                ("files", models.ManyToManyField(to="chat.file")),
                (
                    "links",
                    models.ManyToManyField(related_name="room_link", to="chat.links"),
                ),
                ("media", models.ManyToManyField(to="chat.media")),
                (
                    "participants",
                    models.ManyToManyField(related_name="rooms", to="chat.user"),
                ),
            ],
        ),
    ]
