# Generated by Django 4.2 on 2023-04-14 07:35

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_message_recipient_room_group_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="room",
            field=models.ManyToManyField(to="chat.room"),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="links",
            name="room",
            field=models.ManyToManyField(to="chat.room"),
        ),
        migrations.AddField(
            model_name="links",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="links",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
