# Generated by Django 4.2 on 2023-04-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_file_room_file_user_links_room_links_uploaded_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="room",
        ),
        migrations.RemoveField(
            model_name="file",
            name="user",
        ),
        migrations.RemoveField(
            model_name="links",
            name="room",
        ),
        migrations.RemoveField(
            model_name="links",
            name="user",
        ),
        migrations.AlterField(
            model_name="media",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
        migrations.RemoveField(
            model_name="media",
            name="user",
        ),
        migrations.AddField(
            model_name="file",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="links",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
        migrations.AddField(
            model_name="links",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
