# Generated by Django 4.2 on 2023-04-14 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_file_room_remove_file_user_remove_links_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 14, 7, 50, 8, 568501, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 14, 7, 50, 8, 571579, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
