# Generated by Django 4.2 on 2023-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_links_uploaded_at_alter_media_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="links",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
