# Generated by Django 4.2 on 2023-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_file_uploaded_at_alter_links_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="links",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
