# Generated by Django 4.2 on 2023-04-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_file_uploaded_at_alter_links_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="room",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="room",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room",
            ),
        ),
    ]
