# Generated by Django 4.2 on 2023-04-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_links_room_alter_media_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="links",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="media",
            name="uploaded_at",
        ),
    ]
