# Generated by Django 4.2 on 2023-04-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_links_uploaded_at_remove_media_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="uploaded_at",
        ),
    ]
