# Generated by Django 4.2 on 2023-04-14 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_file_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="links",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="file",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room",
            ),
        ),
    ]
